### ISSUE TITLE
Solo saludar

### ISSUE THREAD

**Issue by ghost** [HorseLuis/MeteoGaliciApp#1]
Estaba intentando montarme una app que pille los datos de meteogalicia para la playa y mareas de mi pueblo, para uso personal. No soy programador, pero cogiendo codigos de aqui y alli a veces monto cosillas. Voy a construir el apk para ver como tienes montada esta. 
Me viene muy bien, tanto para aprender como para intentar forkearla y adaptarmela. Si veo que puedo ayudar en alguna cosa con tu proyecto te hare alguna PR. Tengo algunos Themes para android en F-droid https://gitlab.com/users/xphnx/projects...
Saúde

**Comment by HorseLuis** [comment]
Bueno, esta app solo obtiene datos de temperatura y estado del cielo, pero supongo que puedes utilizar la clase lectora de XML para obtener los datos de la marea desde la web.
